crz:
  charset: 'utf-8'
  credential: ''
engine:
  filter:
    addr: 127.0.0.1:7574
  search:
    addr: 127.0.0.1:7577
spring:
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      globally_quoted_identifiers: true
  redis:
    host: '127.0.0.1'
    port: 6379

ocr:
  addr: 127.0.0.1:62975
  sdk_url: /sdk/ocr
  api_key: SNOCR-40afba5e91fd49b88224e9b76229c8af
  
  